language: php
php:
  - '7.0'
  - '7.1'
  - nightly

addons:
  apt:
    packages:
      - libssl1.0.0

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction

script:
    - vendor/bin/phpunit

