language: php
sudo: false
dist: trusty
php:
  - 5.3
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - nightly

script: phpunit --coverage-clover=coverage.xml

after_success: bash <(curl -s https://codecov.io/bash)    

