language: php
php:
  - '5.3'
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only
  - nightly

addons:
  apt:
    packages:
      - libssl1.0.0

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit

