language: php
sudo: false
dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

before_script: composer dump-autoload

script: phpunit --coverage-clover=coverage.xml

after_success: bash <(curl -s https://codecov.io/bash)

